swagger: "2.0"
info:
  contact:
    name: Kari Kangas (karijkangas@gmail.com)
  description: ""
  license:
    name: MIT
  title: Gotagsavaruus REST API
  version: 0.0.1
host: localhost.com:8000
basePath: /api
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json
paths:
  /signups/check:
    post:
      description: |
        Check account availability. Account is available if there is no existing user registered
        with a given email address.
      parameters:
        - description: Signup check data
          in: body
          name: data
          required: true
          schema:
            $ref: "#/definitions/SignupsCheck"
      produces:
        - application/json
      responses:
        "200":
          description: Account available
        "400":
          description: Invalid data
        "409":
          description: Account not available
  /signups/:
    post:
      description: |
        Create a signup request. Sends an email with a signup verification link.
      parameters:
        - description: Signup data
          in: body
          name: data
          required: true
          schema:
            $ref: "#/definitions/Signup"
      produces:
        - application/json
      responses:
        "200":
          description: Signup request accepted
        "400":
          description: Invalid data
        "409":
          description: Account not available
  /signups/verify:
    post:
      description: |
        Verify signup request. Creates a user account matching the signup request data and
        removes the request. Given password must match the password in the signup request data.
        Returns a session token.
      parameters:
        - description: Signup verify data
          in: body
          name: data
          required: true
          schema:
            $ref: "#/definitions/VerifySignup"
      produces:
        - application/json
      responses:
        "200":
          description: Token
          schema:
            $ref: "#/definitions/Token"
        "404":
          description: Invalid signup request
  /signin/:
    post:
      description: |
        Signin with email and password.
      parameters:
        - description: Signin data
          in: body
          name: data
          required: true
          schema:
            $ref: "#/definitions/Signin"
      produces:
        - application/json
      responses:
        "200":
          description: Token
          schema:
            $ref: "#/definitions/Token"
        "400":
          description: Invalid data
  /resetpw/:
    post:
      description: |
        Create a reset password request. Sends an email with a verification link.
      parameters:
        - description: Reset password data
          in: body
          name: data
          required: true
          schema:
            $ref: "#/definitions/ResetPassword"
      produces:
        - application/json
      responses:
        "201":
          description: Reset password request accepted
          schema:
            $ref: "#/definitions/Token"
        "400":
          description: Invalid data
        "404":
          description: Unknown email
  /resetpw/verify:
    post:
      description: |
        Reset password and remove the request.
      parameters:
        - description: Reset password verify data
          in: body
          name: data
          required: true
          schema:
            $ref: "#/definitions/VerifyResetPassword"
      produces:
        - application/json
      responses:
        "200":
          description: Token.
          schema:
            $ref: "#/definitions/Token"
        "404":
          description: Invalid password reset request
        "410":
          description: User matching email not found
  /auth/account/:
    patch:
      description: |
        Modify account.
      parameters:
        - description: Modify account data
          in: body
          name: data
          required: true
          schema:
            $ref: "#/definitions/ModifyAccount"
      produces:
        - application/json
      responses:
        "200":
          description: Account modified
        "400":
          description: Invalid data
        "401":
          description: Invalid token
    delete:
      description: |
        Delete account.
      parameters:
        - description: Delete account data
          in: body
          name: data
          required: true
          schema:
            $ref: "#/definitions/DeleteAccount"
      produces:
        - application/json
      responses:
        "200":
          description: Account deleted
        "400":
          description: Invalid password
        "401":
          description: Invalid token
definitions:
  SignupsCheck:
    properties:
      email:
        type: string
    required:
      - email
    type: object
  Signup:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    required:
      - name
      - email
      - password
    type: object
  VerifySignup:
    properties:
      id:
        type: string
      password:
        type: string
    required:
      - id
      - password
    type: object
  Signin:
    properties:
      email:
        type: string
      password:
        type: string
    required:
      - email
      - password
    type: object
  Token:
    properties:
      token:
        type: string
    type: object
  ResetPassword:
    properties:
      email:
        type: string
    required:
      - email
    type: object
  VerifyResetPassword:
    properties:
      id:
        type: string
      password:
        type: string
    required:
      - id
      - password
    type: object
  ModifyAccount:
    properties:
      name:
        type: string
      password:
        type: string
    type: object
  DeleteAccount:
    properties:
      password:
        type: string
    required:
      - password
    type: object
